opt_in_rules:

- private_outlet # explicitly
- private_action # explicitly

disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - trailing_whitespace
  - todo
  #- valid_docs
  - force_cast
  - cyclomatic_complexity
  - identifier_name
  - function_parameter_count
  - syntactic_sugar

# parameterized rules are first parameterized as a warning level, then error level.  
line_length: 120
type_body_length: 300
function_body_length: 120

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- FiveAndGo/Common/Extensions/SwiftGen/Storyboards+Swiftgen.swift
- FiveAndGo/Common/Extensions/SwiftGen/Colors+Swiftgen.swift
- FiveAndGo/Common/Extensions/SwiftGen/Fonts+Swiftgen.swift
- FiveAndGo/Common/Extensions/SwiftGen/Strings+Swiftgen.swift
- FiveAndGo/Common/Extensions/SwiftGen/Images+Swiftgen.swift
